// Alle teksten van de app staan hier, zodat vertalen later makkelijk is.
export const texts = {
    appNaam: 'Plantenmaatje',

    titel: 'Mijn plant',
    ondertitel: 'Vul je plant in en check daarna of de plek genoeg licht krijgt.',
    naamLabel: 'Naam van je plant',
    naamPlaceholder: 'bijv. Monstera',
    dagenLabel: 'Dagen tussen water geven',
    dagenPlaceholder: '7',
    opslaanKnop: 'Plant opslaan',
    resultaatLabel: 'Opgeslagen plant',
    resultaatLeeg: 'Nog niets opgeslagen',
    resultaatHint: 'Vul de velden in en tik op Plant opslaan.',
    lichtmetingKnop: 'Bekijk de lichtmeting',

    foutNaam: 'Vul eerst een naam in.',
    foutGetal: 'Vul bij dagen een geldig getal in, bijvoorbeeld 7.',
    foutGeenPlant: 'Sla eerst een plant op.',

    lichtmetingTitel: 'Je plant',
    gemetenLicht: 'Gemeten licht',
    lux: 'lux',
    sensorLabel: 'Bewegingssensor',
    sensorStil: 'Actief — telefoon stil',
    sensorBeweegt: 'Actief — telefoon beweegt',
    locatieLabel: 'Huidige locatie',
    geenToestemming: 'Geen toestemming voor je locatie.',
    meerInfoKnop: 'Meer over deze plant',
    geenLichtsensor: 'Deze telefoon heeft geen lichtsensor.',
    adviesUitleg: 'Dit advies hoort bij de lichtwaarde die nu gemeten wordt.',
    sensorenKnop: 'Beschikbare sensoren',
    sensorenTitel: 'Sensoren',
    sensorenUitleg: 'Dit zijn de sensoren die deze telefoon heeft.',
    beschikbaar: 'Beschikbaar',
    nietBeschikbaar: 'Niet beschikbaar',
    wisKnop: 'Plant wissen',
};